#!/bin/bash
echo "compiling..."
docker run --rm -it -v $PWD:/app -w /app durosoft/crystal-alpine:latest crystal build src/crystal_static_compilation.cr -o crystal_static_compilation --release --static --no-debug
echo "done."
